# SPDX-License-Identifier: GPL-2.0
ccflags-y += -I$(srctree)/sound/soc/sprd/unisoc/codec/ump9620/include
ccflags-y += -I$(srctree)/sound/soc/sprd/unisoc/codec/ump9620/codec
ccflags-y += -I$(srctree)/sound/soc/sprd/unisoc/codec/ump9620/power
obj-$(CONFIG_SND_SOC_UNISOC_CODEC_UMP9620_POWER_DEV) += snd-soc-sprd-codec-ump9620-power-dev.o
snd-soc-sprd-codec-ump9620-power-dev-y := sprd-audio-power-dev.o
