# SPDX-License-Identifier: GPL-2.0
ccflags-y += -I$(srctree)/sound/soc/sprd/unisoc/codec/ump9620/include
ccflags-y += -I$(srctree)/sound/soc/sprd/unisoc/fsa4480
ccflags-y += -DCONFIG_SND_SOC_UNISOC_CODEC_UMP9620
ccflags-y += -DCONFIG_SND_SOC_UNISOC_CODEC_DNS_N6L
ccflags-y += -DCONFIG_SND_SOC_HEADSET_FSA4480
obj-$(CONFIG_SND_SOC_UNISOC_CODEC_UMP9620) += snd-soc-sprd-codec-ump9620.o
snd-soc-sprd-codec-ump9620-y := sprd-codec.o sprd-headset-ump9620.o
