# SPDX-License-Identifier: GPL-2.0
ccflags-y += -I$(srctree)/sound/soc/sprd/unisoc/platform/platform_routing
ccflags-y += -I$(srctree)/sound/soc/sprd/unisoc/platform/dmaengine_pcm
ccflags-y += -DCONFIG_UNISOC_AUDIO_MCDT_R2P0
obj-$(CONFIG_SND_SOC_UNISOC_VBC_V4) += snd-soc-sprd-vbc-v4.o
snd-soc-sprd-vbc-v4-y := vbc-dai.o vbc-phy-v4.o
