# SPDX-License-Identifier: GPL-2.0
ccflags-y += -I$(srctree)/sound/soc/sprd/unisoc/codec/ump9620/include
ccflags-y += -I$(srctree)/sound/soc/sprd/unisoc/codec/ump9620/codec
obj-$(CONFIG_SND_SOC_UNISOC_CODEC_UMP9620_POWER) += snd-soc-sprd-codec-ump9620-power.o
snd-soc-sprd-codec-ump9620-power-y := sprd-audio-power.o
