# SPDX-License-Identifier: GPL-2.0
ccflags-y += -I$(srctree)/sound/soc/sprd/unisoc/platform/dmaengine_pcm
ccflags-y += -DCONFIG_SND_SOC_UNISOC_TDM
obj-$(CONFIG_SND_SOC_UNISOC_TDM) += snd-soc-sprd-tdm.o
snd-soc-sprd-tdm-y := tdm.o
